# Generated by Django 4.0.2 on 2022-03-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Assets',
        ),
    ]
