# Generated by Django 4.0.2 on 2022-03-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0003_assets_year_of_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='fullname',
            new_name='user',
        ),
        migrations.AddField(
            model_name='assets',
            name='accumulated_balance',
            field=models.DecimalField(decimal_places=2, default=202.36, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assets',
            name='historical_cost',
            field=models.DecimalField(decimal_places=2, default=25.36, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assets',
            name='location',
            field=models.CharField(default=12, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assets',
            name='purchase_order',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assets',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=12.32, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assets',
            name='specification',
            field=models.CharField(default=25, max_length=500),
            preserve_default=False,
        ),
    ]
