# Generated by Django 4.0.2 on 2022-03-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0004_rename_fullname_assets_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='accumulated_balance',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='location',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='user',
        ),
        migrations.AddField(
            model_name='assets',
            name='fullname',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
