# Generated by Django 4.0.2 on 2022-03-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0006_remove_assets_historical_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='historical_cost',
            field=models.DecimalField(decimal_places=2, default=20000.35, max_digits=50),
            preserve_default=False,
        ),
    ]
