# Generated by Django 4.0.2 on 2022-03-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0007_assets_historical_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='purchase_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
