# Generated by Django 4.0.2 on 2022-03-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0008_assets_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='user',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
