# Generated by Django 4.0.2 on 2022-03-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0009_assets_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='location',
            field=models.CharField(default=222, max_length=500),
            preserve_default=False,
        ),
    ]
