# Generated by Django 4.0.2 on 2022-03-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0011_assets_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=50),
            preserve_default=False,
        ),
    ]
