# Generated by Django 4.0.2 on 2022-03-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0012_assets_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='accumulated_balance',
            field=models.DecimalField(decimal_places=2, default=777, max_digits=50),
            preserve_default=False,
        ),
    ]
