# Generated by Django 4.0.2 on 2022-03-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0013_assets_accumulated_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='book_value',
            field=models.DecimalField(decimal_places=2, default=8888888, max_digits=50),
            preserve_default=False,
        ),
    ]
