# Generated by Django 4.0.2 on 2022-03-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0014_assets_book_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='mobile',
        ),
    ]
