# Generated by Django 4.0.2 on 2022-03-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0015_remove_assets_fullname_remove_assets_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='emp_code',
        ),
    ]
