# Generated by Django 4.0.2 on 2022-03-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0016_remove_assets_emp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='mainvalue',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=50),
            preserve_default=False,
        ),
    ]
