# Generated by Django 4.0.2 on 2022-03-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0020_assets_bookvalue_assets_from_year_assets_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='bookValue',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='from_year',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='result',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='service_year',
        ),
    ]
