# Generated by Django 4.0.2 on 2022-03-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0023_remove_assets_result_assets_content_assets_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='content',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='title',
        ),
    ]
